---
theme: main
terminal: kitty
packages_file: .chezmoidata/packages.yaml
aurHelper: paru
font:
  size: 14
  size_notifications: 12
  size_qt: 12
  mono: Ubuntu Mono
  regular: Roboto

colors:
  "main":
    "color_1": "C495F0" # Main accents(Purple)
    "color_2": "6CE05C" # Good accents (green mostly)
    "color_3": "FF9BF5" # Different accent (pink)
    "color_4": "68F2E0" # (cyan)
    "color_5": "F01578" # Bad accents (red mostly)
    "color_6": "F3F79E" # Neutral accents (Yellow mostly)
    "foreground": "4D4D4D"
    "background": "4D4D4D"
    "foreground_white": "FFFFFF"
